### ISSUE TITLE
Block command

### ISSUE THREAD

**Issue by AlexMCool** [Arcensoth/cogbot#5]
This feature would allow the user to get information about a certain block.
The command would work similar to `>mcc` (MineCraft Command). A proposed command name would be `>mcb` (MineCraft Block). The syntax could be `>mcc <block>` which would then list the blockstates of the specified block. The information it could return could be expanded if the `blocks.json` report ever gets extended.
Just like the `>mcc` command it would be useful if it could use RegEx for block names.

**Comment by Arcensoth** [comment]
This would be useful.

I'd like to extend mccq for this functionality, but it becomes clear to me that a generalized Minecraft data query program - of which mccq would effectively be a subcommand - would be ideal.

I started a new project [mcdb](https://github.com/Arcensoth/mcdb) for exactly this purpose. Once it's mature enough, I will deprecate mccq and create a new bot extension that uses mcdb for all of commands, blocks, and whatever other kind of data we can query.

The old `>mccq <query>` will turn into something like `>mcdb command <query>` or `>mcdb c <query>` for short.

**Comment by Arcensoth** [comment]
Implemented in: https://github.com/Arcensoth/cogbot/commit/09903dec92d12ce401f257e09b9d6e407103f4e9
